"""Add rooms, hospitalizations, insurances, notifications tables

Revision ID: 0c52c7a61e3e
Revises: 004_passages_motif_varchar
Create Date: 2026-04-06 09:35:09.630369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c52c7a61e3e'
down_revision: Union[str, None] = '004_passages_motif_varchar'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom_compagnie', sa.String(length=150), nullable=False),
    sa.Column('taux_couverture', sa.Integer(), nullable=False),
    sa.Column('plafond_annuel_fcfa', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('exclusions', sa.Text(), nullable=True),
    sa.Column('est_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurances_nom_compagnie'), 'insurances', ['nom_compagnie'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('type_chambre', sa.String(length=30), nullable=False),
    sa.Column('tarif_journalier_fcfa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('est_disponible', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_est_disponible'), 'rooms', ['est_disponible'], unique=False)
    op.create_index(op.f('ix_rooms_numero'), 'rooms', ['numero'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type_notification', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('est_lue', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_est_lue'), 'notifications', ['est_lue'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('hospitalizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('medecin_id', sa.String(length=36), nullable=True),
    sa.Column('date_admission', sa.DateTime(), nullable=False),
    sa.Column('date_sortie', sa.DateTime(), nullable=True),
    sa.Column('motif_hospitalisation', sa.Text(), nullable=True),
    sa.Column('acompte_verse_fcfa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('montant_total_fcfa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitalizations_date_admission'), 'hospitalizations', ['date_admission'], unique=False)
    op.create_index(op.f('ix_hospitalizations_patient_id'), 'hospitalizations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_hospitalizations_room_id'), 'hospitalizations', ['room_id'], unique=False)
    op.create_index(op.f('ix_hospitalizations_statut'), 'hospitalizations', ['statut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_passages_accueil_patient_id'), 'passages_accueil', ['patient_id'], unique=False)
    op.alter_column('passages_accueil', 'motif_consultation',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2000),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.drop_index(op.f('ix_hospitalizations_statut'), table_name='hospitalizations')
    op.drop_index(op.f('ix_hospitalizations_room_id'), table_name='hospitalizations')
    op.drop_index(op.f('ix_hospitalizations_patient_id'), table_name='hospitalizations')
    op.drop_index(op.f('ix_hospitalizations_date_admission'), table_name='hospitalizations')
    op.drop_table('hospitalizations')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_est_lue'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_rooms_numero'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_est_disponible'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_insurances_nom_compagnie'), table_name='insurances')
    op.drop_table('insurances')
    # ### end Alembic commands ###
