"""Add prescriptions and prescription_items tables

Revision ID: c4a3f67e0695
Revises: 0c52c7a61e3e
Create Date: 2026-04-06 09:38:24.392622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4a3f67e0695'
down_revision: Union[str, None] = '0c52c7a61e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('medecin_id', sa.String(length=36), nullable=False),
    sa.Column('passage_accueil_id', sa.String(length=36), nullable=True),
    sa.Column('type_prescription', sa.String(length=30), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['medecin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passage_accueil_id'], ['passages_accueil.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_created_at'), 'prescriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_statut'), 'prescriptions', ['statut'], unique=False)
    op.create_index(op.f('ix_prescriptions_type_prescription'), 'prescriptions', ['type_prescription'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('nom_item', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    op.create_foreign_key(None, 'hospitalizations', 'rooms', ['room_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'hospitalizations', 'users', ['medecin_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'hospitalizations', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'hospitalizations', type_='foreignkey')
    op.drop_constraint(None, 'hospitalizations', type_='foreignkey')
    op.drop_constraint(None, 'hospitalizations', type_='foreignkey')
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_prescriptions_type_prescription'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_statut'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_created_at'), table_name='prescriptions')
    op.drop_table('prescriptions')
    # ### end Alembic commands ###
